# -*- mode: ruby -*-
# vi: set ft=ruby :

##### Libvirt options #####
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.cpu_mode = "host-passthrough"
    libvirt.host = 'localhost'
    libvirt.uri = 'qemu:///system'
    # The default storage pool for libvirt is /var/lib/libvirt, which can be
    # too small on a desktop/laptop computer. If you have a storage pool in
    # your home directory, uncomment the following line
    # and specify the storage pool name.
    # libvirt.storage_pool_name = 'nils-images'
  end

  config.vm.synced_folder "../", "/vagrant", type: "virtiofs"
  config.vm.provider :libvirt do |v|
    v.memory = 512
    v.memorybacking :access, :mode => "shared"
  end

##### Virtual machines options #####
  config.vm.provision :shell, path: "../csl-common/bootstrap.sh"
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false

  (11..13).each do |i|
    config.vm.define "server#{i}" do |node|
      node.vm.hostname = "server#{i}.example.com"
      node.vm.network "forwarded_port", guest: 80, host:"80#{i}", protocol: "tcp", guest_ip: "10.13.37.#{i}"
      node.vm.network "forwarded_port", guest: 22, host:"22#{i}", protocol: "tcp", guest_ip: "10.13.37.#{i}" 
      node.vm.network "forwarded_port", guest: 443, host:"43#{i}", protocol: "tcp", guest_ip: "10.13.37.#{i}"
      node.vm.network "forwarded_port", guest: 8080, host:"88#{i}", protocol: "tcp", guest_ip: "10.13.37.#{i}"
      node.vm.network :private_network,
        :ip => "10.13.37.#{i}",
        :libvirt__network_name => "csl-vagrant-lab",
        :libvirt__netmask => "255.255.255.0"
    end
  end

end
